[cuenta]
usuario = jjbenitez026@gmail.com
password = wxpfNwym@Y8br@*

[producto]
url = https://tiendasolar.com/producto/panel-solar-bifacial-trina-solar-510-wp/
cantidad = 6

[pago]
; metodo: ID del gateway (bipay, bacs, etc.)
metodo = bipay
; red: nombre exacto del método dentro del gateway bipay
; Opciones: Visa, Mastercard, American Express, Dinners Club Internacional,
;           Mastercard Maestro, Tarjeta Virtual, Discover Global, Union Pay, Paypal
red = Visa

[facturacion]
email = jjbenitez026@gmail.com
first_name = Jose Javier
last_name = Hernandez Benítez
address_1 = Calle 184 e 1ra y 5ta edificio BEE1 apt18
address_2 = 
city = La Habana
; state: código ISO de provincia CU (CU-03 = La Habana)
state = CU-03
postcode = 11300
phone = +5355161576
country = CU

[destinatario]
; Datos del destinatario del pedido (campos personalizados de la tienda)
nombre = José Javier
apellidos = Hernández Benítez
; carnet de identidad / documento de identificación
carnet_identidad = 92012633966
telefono = +5355161576
celular = +5355161576

[comportamiento]
; true → solo monta en carrito y notifica. false → flujo completo hasta pago
solo_montar = true

[telegram]
; Token del bot de Telegram y Chat ID del grupo
bot_token = 8211858776:AAFvUMA3JsVQ0o6_uUHe7mxgUwX3zYMopjw
chat_id = -1004452015588
